replicaCount: 1

image:
  repository: hypercoin-dev
  tag: latest
  pullPolicy: Never

containerPort: 80
command: []

service:
  port: 80

ingress:
  enabled: true
  host: hypercoin-dev.local

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
